import { CATALOG, type CatalogEntry } from "./catalog.generated";
import type { IntegrationCategory, IntegrationConnection, IntegrationDefinition } from "./types";

/**
 * Integration catalogue.
 *
 * Two layers:
 *  - `CATALOG` (generated): every service Navio can reach, with its real brand
 *    mark. Regenerated by `scripts/sync-integrations.mjs`, never hand-edited.
 *  - `FIRST_CLASS` (curated): the services with an adapter in this build, which
 *    declare the credentials they need and the tools they expose.
 *
 * Honesty rule: Navio never pretends. A service is "Connected" only when real
 * credentials for it exist in the server environment. Everything else reads
 * "Available", and Navio is told in its system prompt which tools actually
 * exist, so it cannot claim to have used one.
 */

export { CATALOG };
export type { CatalogEntry };

export const CATEGORY_LABEL: Record<string, string> = {
  development: "Development",
  communication: "Communication",
  productivity: "Productivity",
  crm: "CRM & Sales",
  marketing: "Marketing",
  support: "Support",
  finance: "Finance",
  commerce: "Commerce",
  data: "Data & Analytics",
  ai: "AI",
  search: "Search & Enrichment",
  storage: "Storage",
  hr: "People",
  security: "Security",
  other: "More",
};

/** Category order used everywhere the catalogue is grouped. */
export const CATEGORY_ORDER: string[] = [
  "development",
  "communication",
  "productivity",
  "crm",
  "marketing",
  "support",
  "finance",
  "commerce",
  "data",
  "ai",
  "search",
  "storage",
  "hr",
  "security",
  "other",
];

/**
 * Services Navio supports that the logo set has no mark for.
 *
 * The catalogue is generated from brand marks, which means a service without
 * one would otherwise be invisible even though an adapter exists. These are
 * merged in and render as a lettered tile — the honest alternative to drawing
 * someone else's logo ourselves.
 */
const EXTRA_SERVICES: Array<{ slug: string; name: string; category: string }> = [
  { slug: "higgsfield", name: "Higgsfield", category: "ai" },
];

/** Asset path for a service's real brand mark. */
const BY_SLUG = new Map(CATALOG.map((entry) => [entry.slug, entry]));
const FILE_BY_SLUG = new Map(CATALOG.map((entry) => [entry.slug, entry.file]));
export function logoPath(slug: string): string | null {
  const file = FILE_BY_SLUG.get(slug);
  return file ? `/logos/${file}` : null;
}

export function catalogEntry(slug: string): CatalogEntry | undefined {
  return BY_SLUG.get(slug);
}

/**
 * Services with an adapter in this build. `requiredEnv` is what an operator
 * must set for the connection to become real.
 */
export const FIRST_CLASS: IntegrationDefinition[] = [
  {
    id: "github",
    name: "GitHub",
    category: "development",
    description: "Repositories, pull requests, issues and review activity.",
    implemented: true,
    requiredEnv: ["GITHUB_APP_ID", "GITHUB_APP_PRIVATE_KEY"],
  },
  {
    id: "linear",
    name: "Linear",
    category: "development",
    description: "Issues, cycles and project velocity.",
    implemented: true,
    requiredEnv: ["LINEAR_API_KEY"],
  },
  {
    id: "slack",
    name: "Slack",
    category: "communication",
    description: "Channels, threads and direct messages.",
    implemented: true,
    requiredEnv: ["SLACK_BOT_TOKEN"],
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "communication",
    description: "Threads, drafts and scheduled sends.",
    implemented: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "productivity",
    description: "Availability, meetings and agendas.",
    implemented: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  {
    id: "notion",
    name: "Notion",
    category: "productivity",
    description: "Databases, pages and team wikis.",
    implemented: true,
    requiredEnv: ["NOTION_TOKEN"],
  },
  {
    id: "google-meet",
    name: "Google Meet",
    category: "communication",
    description: "Conferencing links attached to the meetings Navio sets up.",
    implemented: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    category: "marketing",
    description: "Company page posts and audience activity.",
    implemented: true,
    requiredEnv: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET"],
  },
  {
    id: "higgsfield",
    name: "Higgsfield",
    category: "ai",
    description: "Generated video for social, rendered from a brief.",
    implemented: true,
    requiredEnv: ["HIGGSFIELD_API_KEY"],
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "marketing",
    description: "Channel uploads, metadata and visibility.",
    implemented: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  {
    id: "twitter",
    name: "X",
    category: "marketing",
    description: "Posts and media on the company account.",
    implemented: true,
    requiredEnv: ["TWITTER_API_KEY", "TWITTER_API_SECRET"],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "finance",
    description: "Revenue, subscriptions and payment health.",
    implemented: true,
    requiredEnv: ["STRIPE_SECRET_KEY"],
  },
];

/** Every service, with the curated detail merged in where it exists. */
export interface CatalogService {
  slug: string;
  name: string;
  category: string;
  logo: string | null;
  description?: string;
  /** True when an adapter exists in this build. */
  implemented: boolean;
  requiredEnv: string[];
  /** The mark is too dark to read unaided on Navio's surfaces. */
  dark: boolean;
}

const FIRST_CLASS_BY_ID = new Map(FIRST_CLASS.map((definition) => [definition.id, definition]));

export function allServices(): CatalogService[] {
  const generated = CATALOG.map((entry) => ({
    slug: entry.slug,
    name: entry.name,
    category: entry.category,
    dark: entry.dark,
  }));

  const extras = EXTRA_SERVICES.filter((extra) => !BY_SLUG.has(extra.slug)).map((extra) => ({
    ...extra,
    dark: false,
  }));

  return [...generated, ...extras].map((entry) => {
    const curated = FIRST_CLASS_BY_ID.get(entry.slug);
    return {
      slug: entry.slug,
      name: curated?.name ?? entry.name,
      category: curated?.category ?? entry.category,
      logo: logoPath(entry.slug),
      description: curated?.description,
      implemented: Boolean(curated?.implemented),
      requiredEnv: curated?.requiredEnv ?? [],
      dark: entry.dark,
    };
  }).sort((a, b) => a.name.localeCompare(b.name));
}

/** Services shown first: the ones with adapters, then the household names. */
export const FEATURED_SLUGS = [
  "github", "slack", "gmail", "notion", "linear", "google-calendar", "stripe", "jira",
  "salesforce", "hubspot", "figma", "airtable", "asana", "shopify", "zoom", "discord",
  "google-drive", "trello", "supabase", "intercom", "zendesk", "clickup", "dropbox", "twilio",
];

export function featuredServices(): CatalogService[] {
  const byId = new Map(allServices().map((service) => [service.slug, service]));
  return FEATURED_SLUGS.map((slug) => byId.get(slug)).filter((service): service is CatalogService =>
    Boolean(service),
  );
}

export function integrationById(id: string): IntegrationDefinition | undefined {
  return FIRST_CLASS.find((integration) => integration.id === id);
}

/**
 * Resolve the true status of an integration from the server environment.
 * Never called from the browser — the result is passed down as plain data.
 */
export function resolveStatus(definition: {
  implemented: boolean;
  requiredEnv: string[];
}): IntegrationConnection["status"] {
  if (!definition.implemented) return "available";
  const configured = definition.requiredEnv.every((name) => {
    const value = process.env[name];
    return typeof value === "string" && value.trim().length > 0;
  });
  return configured ? "connected" : "not_configured";
}

export const STATUS_LABEL: Record<IntegrationConnection["status"], string> = {
  connected: "Connected",
  available: "Available",
  not_configured: "Not connected",
  error: "Needs attention",
};

/** Kept for the workspace store, which seeds one connection row per adapter. */
export const INTEGRATIONS = FIRST_CLASS;

export function byCategory(): Array<{ category: IntegrationCategory; items: IntegrationDefinition[] }> {
  return CATEGORY_ORDER.filter((category) =>
    FIRST_CLASS.some((integration) => integration.category === category),
  ).map((category) => ({
    category: category as IntegrationCategory,
    items: FIRST_CLASS.filter((integration) => integration.category === category),
  }));
}
