import type {
  Agent,
  Approval,
  ActivityEvent,
  Conversation,
  Department,
  KnowledgeSource,
  Message,
  Task,
  Team,
  User,
  Workflow,
  Workspace,
  WorkspaceMember,
} from "./types";

/**
 * Seed workspace.
 *
 * A new Navio instance starts with a populated workspace so the product can be
 * evaluated immediately. Nothing here is a fake integration result: every
 * artefact below is content that lives inside Navio itself.
 */

const DAY = 24 * 60 * 60 * 1000;
const now = Date.now();

export const SEED_USERS: User[] = [
  { id: "usr_burak", name: "Burak Şimşek", email: "burak@meridian.co", avatarInitials: "BŞ", title: "Founder & CEO" },
  { id: "usr_sena", name: "Sena Yalçın", email: "sena@meridian.co", avatarInitials: "SY", title: "Head of Engineering" },
  { id: "usr_marco", name: "Marco Bellini", email: "marco@meridian.co", avatarInitials: "MB", title: "Finance Lead" },
  { id: "usr_ada", name: "Ada Okonjo", email: "ada@meridian.co", avatarInitials: "AO", title: "Growth Lead" },
  { id: "usr_ilker", name: "İlker Demir", email: "ilker@meridian.co", avatarInitials: "İD", title: "Operations" },
];

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: "dep_engineering",
    name: "Engineering",
    description: "Platform, product engineering and reliability.",
    knowledgeScopes: ["engineering", "product", "general"],
  },
  {
    id: "dep_finance",
    name: "Finance",
    description: "Planning, reporting and investor material.",
    knowledgeScopes: ["finance", "general"],
  },
  {
    id: "dep_growth",
    name: "Growth",
    description: "Demand, positioning and lifecycle.",
    knowledgeScopes: ["growth", "product", "general"],
  },
  {
    id: "dep_operations",
    name: "Operations",
    description: "People, process and vendor management.",
    knowledgeScopes: ["operations", "general"],
  },
];

export const SEED_WORKSPACE: Workspace = {
  id: "ws_meridian",
  name: "Meridian",
  slug: "meridian",
  plan: "team",
  createdAt: now - 210 * DAY,
  departments: SEED_DEPARTMENTS,
};

export const SEED_MEMBERS: WorkspaceMember[] = [
  { id: "mem_1", workspaceId: "ws_meridian", userId: "usr_burak", role: "owner", departmentIds: ["dep_operations"], joinedAt: now - 210 * DAY, status: "active" },
  { id: "mem_2", workspaceId: "ws_meridian", userId: "usr_sena", role: "admin", departmentIds: ["dep_engineering"], joinedAt: now - 190 * DAY, status: "active" },
  { id: "mem_3", workspaceId: "ws_meridian", userId: "usr_marco", role: "manager", departmentIds: ["dep_finance"], joinedAt: now - 120 * DAY, status: "active" },
  { id: "mem_4", workspaceId: "ws_meridian", userId: "usr_ada", role: "member", departmentIds: ["dep_growth"], joinedAt: now - 80 * DAY, status: "active" },
  { id: "mem_5", workspaceId: "ws_meridian", userId: "usr_ilker", role: "member", departmentIds: ["dep_operations"], joinedAt: now - 40 * DAY, status: "invited" },
];

export const SEED_TEAMS: Team[] = [
  { id: "team_platform", workspaceId: "ws_meridian", departmentId: "dep_engineering", name: "Platform", memberIds: ["mem_2"] },
  { id: "team_fpa", workspaceId: "ws_meridian", departmentId: "dep_finance", name: "FP&A", memberIds: ["mem_3"] },
  { id: "team_demand", workspaceId: "ws_meridian", departmentId: "dep_growth", name: "Demand", memberIds: ["mem_4"] },
];

export const SEED_AGENTS: Agent[] = [
  {
    id: "agt_release",
    workspaceId: "ws_meridian",
    departmentId: "dep_engineering",
    name: "Release Warden",
    purpose: "Watches the release branch, summarises what changed and flags risky diffs before a cut.",
    role: "wind-code",
    grants: ["knowledge:read", "integrations:use", "agents:run"],
    knowledgeScopes: ["engineering", "product"],
    status: "active",
    createdAt: now - 64 * DAY,
    runsLast30Days: 42,
    successRate: 0.97,
  },
  {
    id: "agt_incident",
    workspaceId: "ws_meridian",
    departmentId: "dep_engineering",
    name: "Incident Scribe",
    purpose: "Builds the incident timeline from the channel and drafts the post-mortem skeleton.",
    role: "wind-reasoning",
    grants: ["knowledge:read", "knowledge:write", "integrations:use"],
    knowledgeScopes: ["engineering", "operations"],
    status: "active",
    createdAt: now - 51 * DAY,
    runsLast30Days: 9,
    successRate: 1,
  },
  {
    id: "agt_close",
    workspaceId: "ws_meridian",
    departmentId: "dep_finance",
    name: "Month-End Close",
    purpose: "Reconciles the monthly figures, explains variances and prepares the board extract.",
    role: "wind-finance",
    grants: ["knowledge:read", "integrations:use"],
    knowledgeScopes: ["finance"],
    status: "active",
    createdAt: now - 96 * DAY,
    runsLast30Days: 6,
    successRate: 0.94,
  },
  {
    id: "agt_runway",
    workspaceId: "ws_meridian",
    departmentId: "dep_finance",
    name: "Runway Sentinel",
    purpose: "Recomputes runway when spend moves and warns before a threshold is crossed.",
    role: "wind-finance",
    grants: ["knowledge:read"],
    knowledgeScopes: ["finance"],
    status: "paused",
    createdAt: now - 88 * DAY,
    runsLast30Days: 0,
    successRate: 0.9,
  },
  {
    id: "agt_signal",
    workspaceId: "ws_meridian",
    departmentId: "dep_growth",
    name: "Market Signal",
    purpose: "Tracks competitive moves and turns them into a weekly briefing with a recommendation.",
    role: "wind-research",
    grants: ["knowledge:read", "integrations:use"],
    knowledgeScopes: ["growth", "product"],
    status: "active",
    createdAt: now - 33 * DAY,
    runsLast30Days: 17,
    successRate: 0.92,
  },
  {
    id: "agt_vendor",
    workspaceId: "ws_meridian",
    departmentId: "dep_operations",
    name: "Vendor Desk",
    purpose: "Reads contracts, surfaces renewal dates and drafts the negotiation position.",
    role: "wind-reasoning",
    grants: ["knowledge:read"],
    knowledgeScopes: ["operations"],
    status: "draft",
    createdAt: now - 12 * DAY,
    runsLast30Days: 0,
    successRate: 0,
  },
];

export const SEED_KNOWLEDGE: KnowledgeSource[] = [
  {
    id: "kb_platform_arch",
    workspaceId: "ws_meridian",
    title: "Platform architecture overview",
    kind: "document",
    scope: "engineering",
    departmentIds: ["dep_engineering"],
    uploadedBy: "usr_sena",
    updatedAt: now - 9 * DAY,
    sizeBytes: 18_400,
    content: [
      "Meridian runs a Next.js front end against a Go API gateway. The gateway fans out to four services:",
      "ingest (event capture), graph (entity resolution), ledger (billing events) and notify (delivery).",
      "Postgres is the system of record; Redis holds session and rate-limit state; object storage holds raw payloads.",
      "Known weak points: the graph service holds a single writer lock during nightly compaction, which is the",
      "cause of the 03:00 latency spike. Ledger reconciliation is idempotent but replays are manual.",
      "Deploys go out behind a feature flag service; rollbacks are a flag flip, not a redeploy.",
    ].join("\n"),
  },
  {
    id: "kb_q3_financials",
    workspaceId: "ws_meridian",
    title: "Q3 financial summary",
    kind: "document",
    scope: "finance",
    departmentIds: ["dep_finance"],
    uploadedBy: "usr_marco",
    updatedAt: now - 5 * DAY,
    sizeBytes: 9_800,
    content: [
      "Q3 ARR closed at 4.12M, up from 3.55M in Q2 (+16.1%). Net revenue retention 114%.",
      "Gross margin 78.4%. Operating expense 1.46M for the quarter, of which 61% is payroll.",
      "Cash at period end 6.9M. Trailing three-month average net burn 385K.",
      "Runway on current burn: 17.9 months. Two enterprise renewals worth 410K land in Q4.",
      "Risk: 22% of ARR sits with the three largest accounts; one is in a procurement review.",
    ].join("\n"),
  },
  {
    id: "kb_security_policy",
    workspaceId: "ws_meridian",
    title: "Security and data handling policy",
    kind: "policy",
    scope: "general",
    departmentIds: [],
    uploadedBy: "usr_burak",
    updatedAt: now - 21 * DAY,
    sizeBytes: 12_200,
    content: [
      "Customer data never leaves the primary region. Access is role-scoped and reviewed quarterly.",
      "Any automated action that sends external communication, modifies production, or changes financial",
      "records requires named human approval and leaves an audit receipt.",
      "Secrets live only in the platform secret store. No credential may be committed or embedded in a client.",
      "Vendor access is least privilege and time-bound; every grant has an expiry.",
    ].join("\n"),
  },
  {
    id: "kb_positioning",
    workspaceId: "ws_meridian",
    title: "Positioning and messaging",
    kind: "note",
    scope: "growth",
    departmentIds: ["dep_growth"],
    uploadedBy: "usr_ada",
    updatedAt: now - 14 * DAY,
    sizeBytes: 6_400,
    content: [
      "We sell to operations leaders at 50-500 person companies who are drowning in coordination work.",
      "The wedge is not 'AI chat'. The wedge is: work that used to need three people and a meeting now",
      "happens as a reviewed, auditable run. Buyers care about control before they care about capability.",
      "Competitive: incumbents lead with model names; we lead with outcomes and receipts.",
    ].join("\n"),
  },
  {
    id: "kb_vendor_contracts",
    workspaceId: "ws_meridian",
    title: "Vendor contracts index",
    kind: "dataset",
    scope: "operations",
    departmentIds: ["dep_operations"],
    uploadedBy: "usr_ilker",
    updatedAt: now - 3 * DAY,
    sizeBytes: 22_100,
    content: [
      "Object storage: 48K/yr, auto-renews 14 Nov, 60-day notice, 3 months' usage below committed tier.",
      "Observability: 71K/yr, renews 2 Feb, usage 22% above commit — overage billed monthly.",
      "Support desk: 18K/yr, renews 30 Sep, seat count 40 against 26 active users.",
      "Data enrichment: 34K/yr, renews 19 Dec, contract allows mid-term downgrade with 30-day notice.",
    ].join("\n"),
  },
  {
    id: "kb_product_roadmap",
    workspaceId: "ws_meridian",
    title: "Product roadmap — current half",
    kind: "document",
    scope: "product",
    departmentIds: ["dep_engineering", "dep_growth"],
    uploadedBy: "usr_sena",
    updatedAt: now - 7 * DAY,
    sizeBytes: 15_600,
    content: [
      "Committed: approvals inbox v2, workspace knowledge scoping, audit export, SSO.",
      "Probable: workflow branching, artifact versioning.",
      "Explicitly not this half: mobile app, on-prem deployment, marketplace.",
      "The approvals inbox is the top-requested item in every enterprise deal review this quarter.",
    ].join("\n"),
  },
];

export const SEED_WORKFLOWS: Workflow[] = [
  {
    id: "flw_release_notes",
    workspaceId: "ws_meridian",
    name: "Release notes from merged work",
    description: "Collects what merged since the last tag, writes the notes, and holds them for a human before publishing.",
    trigger: { kind: "event", description: "A release branch is cut", integrationId: "github" },
    status: "active",
    createdBy: "usr_sena",
    createdAt: now - 58 * DAY,
    lastRunAt: now - 2 * DAY,
    steps: [
      { id: "st1", title: "Collect merged changes", actor: "Wind Code", toolId: "github.list_pull_requests", requiresApproval: false },
      { id: "st2", title: "Group by impact", actor: "Wind Code", requiresApproval: false },
      { id: "st3", title: "Draft the notes", actor: "Wind", requiresApproval: false },
      { id: "st4", title: "Publish to the channel", actor: "Wind", toolId: "slack.post_message", requiresApproval: true },
    ],
  },
  {
    id: "flw_weekly_finance",
    workspaceId: "ws_meridian",
    name: "Monday finance brief",
    description: "Recomputes the week's figures, explains the movement, and posts the brief to the leads.",
    trigger: { kind: "schedule", description: "Every Monday 08:00" },
    status: "active",
    createdBy: "usr_marco",
    createdAt: now - 74 * DAY,
    lastRunAt: now - 6 * DAY,
    steps: [
      { id: "st1", title: "Pull the current figures", actor: "Wind Finance", toolId: "stripe.read_metrics", requiresApproval: false },
      { id: "st2", title: "Explain the variance", actor: "Wind Finance", requiresApproval: false },
      { id: "st3", title: "Write the brief", actor: "Wind", requiresApproval: false },
      { id: "st4", title: "Send to finance leads", actor: "Wind", toolId: "gmail.send_email", requiresApproval: true },
    ],
  },
  {
    id: "flw_contract_review",
    workspaceId: "ws_meridian",
    name: "Contract renewal review",
    description: "Reads a contract before its notice window, extracts the terms that matter and proposes a position.",
    trigger: { kind: "schedule", description: "45 days before any renewal date" },
    status: "draft",
    createdBy: "usr_ilker",
    createdAt: now - 11 * DAY,
    steps: [
      { id: "st1", title: "Extract the key terms", actor: "Wind Data", requiresApproval: false },
      { id: "st2", title: "Compare against usage", actor: "Wind Reasoning", requiresApproval: false },
      { id: "st3", title: "Draft the position", actor: "Wind", requiresApproval: false },
    ],
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: "tsk_board_pack",
    workspaceId: "ws_meridian",
    title: "Prepare the Q3 board pack",
    goal: "Pull the quarter's figures, the product position and the risks into one pack the board can read in ten minutes.",
    status: "needs_approval",
    createdBy: "usr_burak",
    createdAt: now - 3 * 60 * 60 * 1000,
    updatedAt: now - 40 * 60 * 1000,
    artifactIds: ["art_board_pack"],
    steps: [
      { id: "s1", title: "Read the quarter's financials", actor: "Wind Finance", status: "completed", startedAt: now - 3 * 60 * 60 * 1000, finishedAt: now - 175 * 60 * 1000 },
      { id: "s2", title: "Summarise product progress", actor: "Wind Reasoning", status: "completed", startedAt: now - 3 * 60 * 60 * 1000, finishedAt: now - 172 * 60 * 1000 },
      { id: "s3", title: "Assess the concentration risk", actor: "Wind Reasoning", status: "completed", startedAt: now - 170 * 60 * 1000, finishedAt: now - 160 * 60 * 1000 },
      { id: "s4", title: "Assemble the pack", actor: "Wind", status: "completed", startedAt: now - 160 * 60 * 1000, finishedAt: now - 150 * 60 * 1000 },
      { id: "s5", title: "Send to the board list", actor: "Wind", status: "needs_approval", note: "Waiting on a human decision" },
    ],
  },
  {
    id: "tsk_latency",
    workspaceId: "ws_meridian",
    title: "Find the cause of the 03:00 latency spike",
    goal: "Work out why p99 triples at 03:00 and propose a fix that does not require a migration.",
    status: "completed",
    createdBy: "usr_sena",
    createdAt: now - 2 * DAY,
    updatedAt: now - 2 * DAY + 26 * 60 * 1000,
    artifactIds: ["art_latency"],
    steps: [
      { id: "s1", title: "Read the service topology", actor: "Wind Code", status: "completed" },
      { id: "s2", title: "Correlate with the job schedule", actor: "Wind Data", status: "completed" },
      { id: "s3", title: "Assess the fix options", actor: "Wind Reasoning", status: "completed" },
      { id: "s4", title: "Write the recommendation", actor: "Wind", status: "completed" },
    ],
  },
  {
    id: "tsk_renewals",
    workspaceId: "ws_meridian",
    title: "Review vendor renewals for the next 90 days",
    goal: "Identify which renewals are mispriced against actual usage and what the notice windows are.",
    status: "running",
    createdBy: "usr_ilker",
    createdAt: now - 18 * 60 * 1000,
    updatedAt: now - 2 * 60 * 1000,
    artifactIds: [],
    steps: [
      { id: "s1", title: "Extract contract terms", actor: "Wind Data", status: "completed", startedAt: now - 18 * 60 * 1000, finishedAt: now - 14 * 60 * 1000 },
      { id: "s2", title: "Compare commit against usage", actor: "Wind Finance", status: "running", startedAt: now - 14 * 60 * 1000 },
      { id: "s3", title: "Propose a position per vendor", actor: "Wind Reasoning", status: "waiting" },
    ],
  },
];

export const SEED_APPROVALS: Approval[] = [
  {
    id: "apr_board_email",
    workspaceId: "ws_meridian",
    title: "Send the Q3 pack to the board list",
    summary: "One email to 5 recipients with the assembled pack attached as a link.",
    payload: [
      "To: board@meridian.co (5 recipients)",
      "Subject: Q3 pack — figures, product, risks",
      "",
      "Ahead of Thursday: ARR closed at 4.12M (+16.1% on Q2), NRR 114%, gross margin 78.4%.",
      "Net burn averaged 385K over the quarter, leaving 17.9 months of runway on 6.9M cash.",
      "",
      "Product shipped approvals v2 and knowledge scoping; SSO slips two weeks against plan.",
      "",
      "One risk needs a decision: 22% of ARR sits with three accounts and one is in procurement review.",
      "Full pack: [Navio artifact link]",
    ].join("\n"),
    toolId: "gmail.send_email",
    integrationId: "gmail",
    risk: "high",
    status: "pending",
    requestedBy: "usr_burak",
    requestedByAgent: "Wind",
    createdAt: now - 40 * 60 * 1000,
    taskId: "tsk_board_pack",
  },
  {
    id: "apr_release_post",
    workspaceId: "ws_meridian",
    title: "Post release notes to #engineering",
    summary: "Publish the 2.14 notes to the engineering channel.",
    payload: [
      "Channel: #engineering",
      "",
      "*Release 2.14*",
      "• Approvals inbox now groups by risk, not by time",
      "• Knowledge scoping honours department boundaries on every read",
      "• Fixed: compaction lock held through the nightly window",
      "Rollback is a flag flip on `approvals_v2`.",
    ].join("\n"),
    toolId: "slack.post_message",
    integrationId: "slack",
    risk: "medium",
    status: "pending",
    requestedBy: "usr_sena",
    requestedByAgent: "Release Warden",
    createdAt: now - 4 * 60 * 60 * 1000,
  },
  {
    id: "apr_downgrade",
    workspaceId: "ws_meridian",
    title: "Downgrade the support desk seat count",
    summary: "Reduce from 40 seats to 30 before the 30 Sep renewal.",
    payload: "Vendor: support desk. Change: 40 → 30 seats. Effective: next renewal. Saving: 4.5K/yr.",
    risk: "medium",
    status: "approved",
    requestedBy: "usr_ilker",
    requestedByAgent: "Vendor Desk",
    createdAt: now - 2 * DAY,
    decidedAt: now - 2 * DAY + 90 * 60 * 1000,
    decidedBy: "usr_burak",
    decisionNote: "Approved — keep two spare seats for contractors.",
    receipt: "Recorded. No external system was contacted: this vendor is not connected to Navio.",
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  { id: "cnv_board", workspaceId: "ws_meridian", userId: "usr_burak", title: "Q3 board pack", createdAt: now - 3 * 60 * 60 * 1000, updatedAt: now - 40 * 60 * 1000, pinned: true },
  { id: "cnv_latency", workspaceId: "ws_meridian", userId: "usr_burak", title: "03:00 latency spike", createdAt: now - 2 * DAY, updatedAt: now - 2 * DAY },
  { id: "cnv_renewals", workspaceId: "ws_meridian", userId: "usr_burak", title: "Vendor renewals", createdAt: now - 18 * 60 * 1000, updatedAt: now - 2 * 60 * 1000 },
  { id: "cnv_positioning", workspaceId: "ws_meridian", userId: "usr_burak", title: "Positioning rewrite", createdAt: now - 5 * DAY, updatedAt: now - 5 * DAY },
];

export const SEED_MESSAGES: Message[] = [
  {
    id: "msg_1",
    conversationId: "cnv_latency",
    role: "user",
    content: "p99 triples at 03:00 every night. Find the cause and propose a fix that does not need a migration.",
    createdAt: now - 2 * DAY,
  },
  {
    id: "msg_2",
    conversationId: "cnv_latency",
    role: "assistant",
    createdAt: now - 2 * DAY + 3 * 60 * 1000,
    content: [
      "The spike is the graph service's nightly compaction, not load.",
      "",
      "**What is happening.** Compaction takes a single writer lock for the whole pass. Reads queue behind it, so p99 climbs while median stays flat — which is the shape in your graphs.",
      "",
      "**Fix without a migration.** Chunk the compaction into per-tenant passes and release the lock between chunks. That keeps the existing schema and turns one long lock into many short ones.",
      "",
      "**Second option, cheaper to ship.** Move compaction to 04:30 and cap concurrency at one. It moves the spike rather than removing it, so treat it as a stopgap.",
      "",
      "I would ship the chunked pass. The risk is a partially compacted state if a chunk fails mid-run — that needs an idempotent resume before it goes out.",
    ].join("\n"),
    trace: [
      { id: "t1", label: "Engineering analysis", actor: "Wind Code", status: "completed", startedAt: now - 2 * DAY, finishedAt: now - 2 * DAY + 90_000 },
      { id: "t2", label: "Risk and trade-offs", actor: "Wind Reasoning", status: "completed", startedAt: now - 2 * DAY + 90_000, finishedAt: now - 2 * DAY + 160_000 },
    ],
  },
];

export const SEED_ACTIVITY: ActivityEvent[] = [
  { id: "act_1", workspaceId: "ws_meridian", kind: "task.started", actor: "Burak Şimşek", summary: "Started “Prepare the Q3 board pack”", at: now - 3 * 60 * 60 * 1000, taskId: "tsk_board_pack" },
  { id: "act_2", workspaceId: "ws_meridian", kind: "knowledge.searched", actor: "Wind", summary: "Searched workspace knowledge — 3 sources matched", at: now - 3 * 60 * 60 * 1000 + 20_000, taskId: "tsk_board_pack" },
  { id: "act_3", workspaceId: "ws_meridian", kind: "specialist.started", actor: "Wind Finance", summary: "Financial analysis started", at: now - 3 * 60 * 60 * 1000 + 25_000, taskId: "tsk_board_pack" },
  { id: "act_4", workspaceId: "ws_meridian", kind: "specialist.completed", actor: "Wind Finance", summary: "Financial analysis completed", at: now - 175 * 60 * 1000, taskId: "tsk_board_pack" },
  { id: "act_5", workspaceId: "ws_meridian", kind: "specialist.completed", actor: "Wind Reasoning", summary: "Risk assessment completed", at: now - 160 * 60 * 1000, taskId: "tsk_board_pack" },
  { id: "act_6", workspaceId: "ws_meridian", kind: "approval.requested", actor: "Wind", summary: "Approval requested: send the Q3 pack to the board list", at: now - 40 * 60 * 1000, approvalId: "apr_board_email", taskId: "tsk_board_pack" },
  { id: "act_7", workspaceId: "ws_meridian", kind: "approval.decided", actor: "Burak Şimşek", summary: "Approved: downgrade the support desk seat count", at: now - 2 * DAY + 90 * 60 * 1000, approvalId: "apr_downgrade" },
  { id: "act_8", workspaceId: "ws_meridian", kind: "task.completed", actor: "Wind", summary: "Completed “Find the cause of the 03:00 latency spike”", at: now - 2 * DAY + 26 * 60 * 1000, taskId: "tsk_latency" },
  { id: "act_9", workspaceId: "ws_meridian", kind: "knowledge.added", actor: "İlker Demir", summary: "Added “Vendor contracts index” to workspace knowledge", at: now - 3 * DAY },
  { id: "act_10", workspaceId: "ws_meridian", kind: "flow.run", actor: "Monday finance brief", summary: "Flow run completed — brief prepared, sending held for approval", at: now - 6 * DAY },
];
